import {useEffect,useState} from 'react'
import {CheckCircle2,GitBranch,KeyRound,PlugZap,Save,UploadCloud} from 'lucide-react'
import {api} from '../api'
import {Header} from '../components'
import type {GitConfiguration,LlmConfiguration,PermissionMode} from '../types'

export default function SettingsPage(){
  const[config,setConfig]=useState<LlmConfiguration>({configured:false}),[gitConfig,setGitConfig]=useState<GitConfiguration>({configured:false}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'llm'|'git'>('llm')
  useEffect(()=>{Promise.all([api.llmConfig(),api.gitConfig()]).then(([llm,git])=>{setConfig(llm);setGitConfig(git)}).catch(e=>setError(e.message))},[])
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await api.saveLlmConfig({base_url:f.get('base_url'),api_key:f.get('api_key')||null,auth_type:f.get('auth_type'),model:f.get('model'),small_fast_model:f.get('small_fast_model')||null,timeout_seconds:Number(f.get('timeout_seconds')),max_turns:Number(f.get('max_turns')),default_permission_mode:f.get('default_permission_mode') as PermissionMode});setConfig(result);setNotice('LLM 配置已加密保存')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function test(deep:boolean){setBusy(true);setError('');try{const r=await api.testLlmConfig(deep);setNotice((deep?'Agent 深度测试：':'连接测试：')+r.message);setConfig(await api.llmConfig())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function saveGit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await api.saveGitConfig({remote_url:f.get('remote_url'),username:f.get('username'),password:f.get('password')||null,auto_push:f.get('auto_push')==='on'});setGitConfig(result);setNotice('远程 Git 配置已加密保存')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function testGit(){setBusy(true);setError('');try{const result=await api.testGitConfig();setNotice(result.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function switchTab(next:'llm'|'git'){setTab(next);setNotice('');setError('')}
  return <div className="settings-shell"><Header title="系统设置" subtitle="配置策略 Agent 与独立策略 Git 仓库。"/>{error&&<div className="form-error">{error}</div>}{notice&&<div className="save-notice"><CheckCircle2/>{notice}</div>}<div className="settings-tabs" role="tablist" aria-label="设置分类"><button type="button" role="tab" aria-selected={tab==='llm'} className={tab==='llm'?'active':''} onClick={()=>switchTab('llm')}><KeyRound/>LLM 配置</button><button type="button" role="tab" aria-selected={tab==='git'} className={tab==='git'?'active':''} onClick={()=>switchTab('git')}><GitBranch/>策略 Git 仓库</button></div><section className="card settings-page" role="tabpanel">{tab==='llm'?<LlmSettings config={config} busy={busy} save={save} test={test}/>:<GitSettings config={gitConfig} busy={busy} save={saveGit} test={testGit}/>}</section></div>
}

function LlmSettings({config,busy,save,test}:{config:LlmConfiguration;busy:boolean;save:(e:React.FormEvent<HTMLFormElement>)=>void;test:(deep:boolean)=>void}){
  return <><div className="section-title"><div><h3><KeyRound/>LLM 配置</h3><p>全系统唯一配置；API Key 加密保存且不会返回前端。</p></div>{config.configured&&<span className={config.last_test_ok?'config-ok':'config-pending'}>{config.last_test_ok?'连接正常':'等待测试'}</span>}</div><form className="stack-form settings-grid" onSubmit={save}><label className="wide">Anthropic API Base URL<input name="base_url" required defaultValue={config.base_url??''} placeholder="https://api.anthropic.com"/></label><label>认证方式<select name="auth_type" defaultValue={config.auth_type??'api_key'}><option value="api_key">x-api-key</option><option value="auth_token">Authorization Bearer</option></select></label><label>API Key<input name="api_key" type="password" placeholder={config.api_key_masked??'请输入 API Key'}/></label><label>模型<input name="model" required defaultValue={config.model??''} placeholder="claude-sonnet-4-6"/></label><label>小模型（可选）<input name="small_fast_model" defaultValue={config.small_fast_model??''}/></label><label>超时（秒）<input name="timeout_seconds" type="number" min="10" max="1800" defaultValue={config.timeout_seconds??120}/></label><label>最大 Agent 轮次<input name="max_turns" type="number" min="1" max="200" defaultValue={config.max_turns??30}/></label><label>默认权限模式<select name="default_permission_mode" defaultValue={config.default_permission_mode??'default'}><option value="plan">Plan</option><option value="default">审批执行</option><option value="acceptEdits">自动编辑</option><option value="bypassPermissions">完全自动</option></select></label><div className="wide settings-actions"><button className="button primary" disabled={busy}><Save/>保存</button><button type="button" className="button" disabled={busy||!config.configured} onClick={()=>test(false)}><PlugZap/>测试连接</button><button type="button" className="button" disabled={busy||!config.configured} onClick={()=>test(true)}><PlugZap/>深度测试 Agent</button></div></form></>
}

function GitSettings({config,busy,save,test}:{config:GitConfiguration;busy:boolean;save:(e:React.FormEvent<HTMLFormElement>)=>void;test:()=>void}){
  return <><div className="section-title"><div><h3><GitBranch/>策略 Git 仓库</h3><p>策略版本提交到独立仓库；密码或访问令牌加密保存且不会返回前端。</p></div></div><form className="stack-form settings-grid" onSubmit={save}><label className="wide">本地策略仓库<input readOnly value={config.repository_path??''}/></label><label className="wide">远程 HTTPS 地址<input name="remote_url" type="url" required defaultValue={config.remote_url??''} placeholder="https://github.com/example/strategies.git"/></label><label>Git 账号<input name="username" required defaultValue={config.username??''}/></label><label>密码或访问令牌<input name="password" type="password" placeholder={config.password_masked??'请输入密码或令牌'}/></label><label className="wide checkbox-label"><input name="auto_push" type="checkbox" defaultChecked={config.auto_push??true}/>发布策略版本后自动推送到远程仓库</label><div className="wide settings-actions"><button className="button primary" disabled={busy}><Save/>保存 Git 配置</button><button type="button" className="button" disabled={busy||!config.configured} onClick={test}><UploadCloud/>测试并推送</button></div></form></>
}
