import {useEffect,useMemo,useState} from 'react'
import {Archive,Check,Code2,LayoutGrid,List,Pencil,Plus,Search,Trash2,X} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {api} from '../api'
import {Card,ConfirmDialog} from '../components'
import {loadCategories,saveCategories} from '../categories'
import type {Strategy,StrategyFile} from '../types'

type Item={file:StrategyFile;strategy?:Strategy}
export default function Strategies(){
  const nav=useNavigate(),[strategies,setStrategies]=useState<Strategy[]>([]),[files,setFiles]=useState<StrategyFile[]>([])
  const[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[view,setView]=useState<'cards'|'list'>('cards'),[newTag,setNewTag]=useState(false),[query,setQuery]=useState(''),[selectedCategory,setSelectedCategory]=useState('全部'),[error,setError]=useState('')
  const[categoryList,setCategoryList]=useState(loadCategories),[managingCategories,setManagingCategories]=useState(false),[newCategory,setNewCategory]=useState(''),[confirmAction,setConfirmAction]=useState<{title:string;message:string;label:string;danger?:boolean;run:()=>Promise<void>}|null>(null)
  async function reload(){const[s,f]=await Promise.all([api.strategies(),api.strategyFiles()]);setStrategies(s);setFiles(f)}
  useEffect(()=>{reload().catch(e=>setError(e.message))},[])
  const items=useMemo<Item[]>(()=>files.map(file=>({file,strategy:strategies.find(s=>s.module===file.module)})),[files,strategies])
  const category=(item:Item)=>item.strategy?.category??item.file.draft_category??'未分类'
  const categories=useMemo(()=>['全部',...Array.from(new Set([...categoryList,...items.map(category).filter(value=>value!=='归档')])).filter(value=>value&&value!=='全部'),'归档'], [items,categoryList])
  const editableCategories=categories.filter(value=>value!=='全部'&&value!=='归档')
  const filtered=useMemo(()=>{const value=query.trim().toLowerCase();return items.filter(item=>{const{file,strategy}=item;const matchesCategory=selectedCategory==='全部'||category(item)===selectedCategory;const matchesQuery=!value||[file.name,file.filename,strategy?.name,strategy?.description,file.draft_description,category(item)].some(x=>x?.toLowerCase().includes(value));return matchesCategory&&matchesQuery})},[items,query,selectedCategory])
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const selected=String(newTag?f.get('new_category'):f.get('category')).trim();try{const file=await api.createStrategyFile(String(f.get('name')),String(f.get('mode')),String(f.get('description')),selected);if(newTag&&!categoryList.includes(selected))persistCategories([...categoryList,selected]);nav('/strategies/'+file.name)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function persistCategories(value:string[]){setCategoryList(saveCategories(value))}
  async function moveCategory(from:string,to:string){for(const item of items.filter(value=>category(value)===from)){if(item.strategy)await api.updateStrategy(item.strategy.id,{category:to});else await api.updateStrategyFileMetadata(item.file.name,item.file.draft_description??'策略说明',to)}await reload()}
  function renameCategory(index:number,value:string){const from=categoryList[index],to=value.trim();if(!to||to===from)return;if(categories.includes(to)){setError(`分类“${to}”已存在`);return}setConfirmAction({title:'重命名分类',message:`将分类“${from}”重命名为“${to}”？该分类下的策略会同步迁移。`,label:'确认重命名',run:async()=>{await moveCategory(from,to);persistCategories(categoryList.map(item=>item===from?to:item));if(selectedCategory===from)setSelectedCategory(to)}})}
  function deleteCategory(value:string){setConfirmAction({title:'删除分类',message:`删除分类“${value}”？该分类下的策略会迁移到“未分类”。`,label:'删除分类',danger:true,run:async()=>{if(items.some(item=>category(item)===value))await moveCategory(value,'未分类');persistCategories(categoryList.filter(item=>item!==value).concat(categoryList.includes('未分类')?[]:['未分类']));if(selectedCategory===value)setSelectedCategory('全部')}})}
  function archive(item:Item){const label=item.strategy?.name??item.file.name;setConfirmAction({title:'归档策略',message:`将策略“${label}”归档？归档后可在“归档”分类中找到。`,label:'确认归档',run:async()=>{if(item.strategy)await api.updateStrategy(item.strategy.id,{category:'归档'});else await api.updateStrategyFileMetadata(item.file.name,item.file.draft_description??'已归档策略','归档');await reload()}})}
  function unarchive(item:Item,target:string){setBusy(true);setError('');const action=item.strategy?api.updateStrategy(item.strategy.id,{category:target}):api.updateStrategyFileMetadata(item.file.name,item.file.draft_description??'策略说明',target);action.then(reload).catch(e=>setError((e as Error).message)).finally(()=>setBusy(false))}
  function remove(item:Item){const label=item.strategy?.name??item.file.name;setConfirmAction({title:'删除策略',message:`确定删除策略“${label}”吗？关联的全部回测记录和报告文件也会永久删除，此操作不能撤销。`,label:'永久删除',danger:true,run:async()=>{if(item.strategy)await api.deleteStrategy(item.strategy.id);await api.deleteStrategyFile(item.file.name);await reload()}})}
  async function executeConfirmed(){if(!confirmAction)return;setBusy(true);setError('');try{await confirmAction.run();setConfirmAction(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function time(item:Item,kind:'created'|'updated'){const db=kind==='created'?item.strategy?.created_at:item.strategy?.updated_at;const file=kind==='created'?item.file.created_at:item.file.updated_at;const value=db??(file?new Date(file*1000).toISOString():null);return value?new Date(value).toLocaleString():'—'}
  return <>
    {error&&<div className="form-error strategy-error">{error}</div>}
    <div className="strategy-category-tabs">{categories.map(value=><button className={selectedCategory===value?'active':''} onClick={()=>setSelectedCategory(value)} key={value}>{value}<span>{value==='全部'?items.length:items.filter(item=>category(item)===value).length}</span></button>)}<button className="category-edit-button" title="管理分类" aria-label="管理分类" onClick={()=>setManagingCategories(true)}><Pencil/></button></div>
    <div className="strategy-controls">
      <div className="strategy-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索策略名称、说明、分类或文件名"/><span>{filtered.length} 个策略</span></div>
      <div className="strategy-actions-bar">
        <div className="view-switch"><button className={view==='cards'?'active':''} onClick={()=>setView('cards')} title="卡片视图"><LayoutGrid/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} title="列表视图"><List/></button></div>
        <button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/>新建策略</button>
      </div>
    </div>
    <div className={'strategy-grid '+(view==='list'?'list-view':'')}>{filtered.map(item=>{const{file,strategy}=item;const archived=category(item)==='归档';return <Card key={file.name} className="clickable-strategy"><button className="card-link" onClick={()=>nav('/strategies/'+file.name)} aria-label={`打开 ${file.name}`}/><div className="strategy-card-actions">{archived?<select aria-label="取消归档并移动到分类" defaultValue="" disabled={busy} onClick={event=>event.stopPropagation()} onChange={event=>{if(event.target.value)unarchive(item,event.target.value)}}><option value="" disabled>取消归档到…</option>{editableCategories.map(value=><option key={value}>{value}</option>)}</select>:<button title="归档策略" onClick={()=>archive(item)}><Archive/></button>}<button title="删除策略" onClick={()=>remove(item)}><Trash2/></button></div>
      <h2>{strategy?.name??file.name}</h2><p>{strategy?.description??file.draft_description??'尚未发布，点击进入编辑代码和完善策略。'}</p>
      <div className="tags"><span>{category(item)}</span><span>{strategy?`v${strategy.version}`:'未发布'}</span></div>
      <dl className="strategy-times"><div><dt>创建时间</dt><dd>{time(item,'created')}</dd></div><div><dt>最新修改</dt><dd>{time(item,'updated')}</dd></div></dl><div className="open-hint"><Code2 size={14}/>进入开发与版本管理 →</div>
    </Card>})}</div>
    {creating&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setCreating(false)}><X/></button><h2>新建策略</h2><p className="muted">选择分类后创建策略并进入开发。</p><form className="stack-form create-strategy-form" onSubmit={create}><label>策略文件名<input name="name" required pattern="[a-z][a-z0-9_]{1,63}" placeholder="mean_reversion"/><small>小写字母、数字和下划线</small></label><label>策略说明<textarea name="description" required maxLength={500} placeholder="说明策略逻辑、适用市场或研究目标"/></label><label>策略分类{newTag?<input name="new_category" required maxLength={50} placeholder="填写新分类"/>:<select name="category" required defaultValue={editableCategories[0]??'趋势'}>{editableCategories.map(tag=><option key={tag}>{tag}</option>)}</select>}<button type="button" className="text-button" onClick={()=>setNewTag(!newTag)}>{newTag?'选择已有分类':'＋ 新建分类'}</button></label><details className="advanced-options"><summary>高级选项</summary><label>策略模式<select name="mode" defaultValue="PORTFOLIO"><option value="PORTFOLIO">组合策略（推荐）</option><option value="SINGLE_INSTRUMENT">单标的策略</option></select></label></details><div className="create-actions"><button className="button primary" disabled={busy}>{busy?'创建中…':'创建并开始开发'}</button></div></form></section></div>}
    {managingCategories&&<div className="modal-backdrop"><section className="modal category-manager"><button className="modal-close" onClick={()=>setManagingCategories(false)}><X/></button><h2>管理策略分类</h2><p className="muted">重命名或删除分类时，该分类下的策略会同步迁移。</p><div className="category-manager-list">{categoryList.map((value,index)=><div className="category-manager-row" key={`${value}-${index}`}><input defaultValue={value} maxLength={50} aria-label={`分类 ${value}`} onKeyDown={event=>{if(event.key==='Enter')renameCategory(index,event.currentTarget.value)}}/><button className="button" title="保存名称" onClick={event=>renameCategory(index,(event.currentTarget.previousElementSibling as HTMLInputElement).value)}><Check/></button><button className="button danger" title="删除分类" onClick={()=>deleteCategory(value)}><Trash2/></button></div>)}</div><div className="category-add"><input value={newCategory} maxLength={50} placeholder="新分类名称" onChange={event=>setNewCategory(event.target.value)}/><button className="button primary" onClick={()=>{const value=newCategory.trim();if(!value)return;if(categories.includes(value)){setError(`分类“${value}”已存在`);return}persistCategories([...categoryList,value]);setNewCategory('')}}><Plus/>新增分类</button></div></section></div>}
    <ConfirmDialog open={!!confirmAction} title={confirmAction?.title??''} message={confirmAction?.message??''} confirmLabel={confirmAction?.label} danger={confirmAction?.danger} busy={busy} onCancel={()=>setConfirmAction(null)} onConfirm={executeConfirmed}/>
  </>
}
