import type {AgentSession,AgentStoredMessage,ChartData,GitConfiguration,LlmConfiguration,PermissionMode,ResearchDecision,ResearchMessage,ResearchProject,ResearchRun,Run,Strategy,StrategyFile,StrategyGitStatus,StrategyVersion} from './types'
const BASE=import.meta.env.VITE_API_URL??'http://localhost:8000/api'
export const agentSocketUrl=(sessionId:string)=>`${BASE.replace(/^http/,'ws')}/agent/ws/${sessionId}`
function errorText(detail:unknown):string{if(typeof detail==='string')return detail;if(Array.isArray(detail))return detail.map(x=>{if(typeof x==='object'&&x){const e=x as {loc?:unknown[];msg?:string};return `${e.loc?.slice(1).join('.')||'参数'}：${e.msg||'格式错误'}`}return String(x)}).join('；');if(detail&&typeof detail==='object')return JSON.stringify(detail);return '请求失败'}
async function request<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(BASE+path,{...init,headers:{'Content-Type':'application/json',...(init?.headers??{})}});if(!r.ok){let body:{detail?:unknown}={};try{body=await r.json()}catch{/**/}throw new Error(errorText(body.detail))}if(r.status===204)return undefined as T;return r.json()}
export const api={
  strategies:()=>request<Strategy[]>('/strategies'),
  strategy:(id:string)=>request<Strategy>('/strategies/'+id),
  createStrategy:(module:string,versionDescription:string)=>request<Strategy>('/strategies',{method:'POST',body:JSON.stringify({module,version_description:versionDescription})}),
  updateStrategy:(id:string,data:unknown)=>request<Strategy>('/strategies/'+id,{method:'PATCH',body:JSON.stringify(data)}),
  deleteStrategy:(id:string)=>request<void>('/strategies/'+id,{method:'DELETE'}),
  versions:(id:string)=>request<StrategyVersion[]>('/strategies/'+id+'/versions'),
  createVersion:(id:string,module:string,description:string)=>request<StrategyVersion>('/strategies/'+id+'/versions',{method:'POST',body:JSON.stringify({module,description})}),
  deleteVersion:(strategyId:string,versionId:string)=>request<void>(`/strategies/${strategyId}/versions/${versionId}`,{method:'DELETE'}),
  restoreVersion:(strategyId:string,versionId:string)=>request<{ok:boolean;message:string}>(`/strategies/${strategyId}/versions/${versionId}/restore`,{method:'POST'}),
  strategyFiles:()=>request<StrategyFile[]>('/strategy-files'),
  strategyFile:(name:string)=>request<StrategyFile>('/strategy-files/'+name),
  createStrategyFile:(name:string,mode:string,description:string,category:string)=>request<StrategyFile>('/strategy-files',{method:'POST',body:JSON.stringify({name,mode,description,category})}),
  saveStrategyFile:(name:string,content:string)=>request<StrategyFile>('/strategy-files/'+name,{method:'PUT',body:JSON.stringify({content})}),
  updateStrategyFileMetadata:(name:string,description:string,category:string)=>request<StrategyFile>(`/strategy-files/${name}/metadata`,{method:'PATCH',body:JSON.stringify({description,category})}),
  deleteStrategyFile:(name:string)=>request<void>('/strategy-files/'+name,{method:'DELETE'}),
  strategyGitStatus:()=>request<StrategyGitStatus>('/strategy-files/git/status'),
  commitStrategyFiles:(message:string)=>request<{commit:string;message:string}>('/strategy-files/git/commit',{method:'POST',body:JSON.stringify({message})}),
  llmConfig:()=>request<LlmConfiguration>('/settings/llm'),
  saveLlmConfig:(data:unknown)=>request<LlmConfiguration>('/settings/llm',{method:'PUT',body:JSON.stringify(data)}),
  testLlmConfig:(deep=false)=>request<{ok:boolean;message:string}>(`/settings/llm/test?deep=${deep}`,{method:'POST'}),
  testHermesConfig:()=>request<{ok:boolean;message:string}>('/settings/llm/test-hermes',{method:'POST'}),
  gitConfig:()=>request<GitConfiguration>('/settings/git'),
  saveGitConfig:(data:unknown)=>request<GitConfiguration>('/settings/git',{method:'PUT',body:JSON.stringify(data)}),
  testGitConfig:()=>request<{ok:boolean;message:string}>('/settings/git/test',{method:'POST'}),
  backupGit:()=>request<{ok:boolean;message:string;files_count:number;commit?:string}>('/settings/git/backup',{method:'POST'}),
  createAgentSession:(client_id:string,strategy_name:string,permission_mode:PermissionMode)=>request<AgentSession>('/agent/sessions',{method:'POST',body:JSON.stringify({client_id,strategy_name,permission_mode})}),
  agentSessions:(clientId:string,strategyName:string)=>request<AgentSession[]>(`/agent/sessions?client_id=${encodeURIComponent(clientId)}&strategy_name=${encodeURIComponent(strategyName)}`),
  agentMessages:(sessionId:string)=>request<AgentStoredMessage[]>(`/agent/sessions/${sessionId}/messages`),
  agentDiff:(sessionId:string)=>request<{diff:string;files:{path:string;additions:number;deletions:number}[];additions:number;deletions:number}>(`/agent/sessions/${sessionId}/diff`),
  applyAgent:(sessionId:string)=>request<{applied:boolean;requires_publish_confirmation:boolean}>(`/agent/sessions/${sessionId}/apply`,{method:'POST',body:JSON.stringify({create_version:false})}),
  rejectAgent:(sessionId:string)=>request<{rejected:boolean}>(`/agent/sessions/${sessionId}/reject`,{method:'POST'}),
  cancelAgent:(sessionId:string)=>request<AgentSession>(`/agent/sessions/${sessionId}/cancel`,{method:'POST'}),
  researchProjects:(clientId:string)=>request<ResearchProject[]>(`/research?client_id=${encodeURIComponent(clientId)}`),
  createResearch:(client_id:string,title:string)=>request<ResearchProject>('/research',{method:'POST',body:JSON.stringify({client_id,title})}),
  researchProject:(id:string)=>request<ResearchProject>('/research/'+id),
  researchMessages:(id:string)=>request<ResearchMessage[]>(`/research/${id}/messages`),
  sendResearchMessage:(id:string,content:string)=>request<{role:string;content:string;decisions:ResearchDecision[]}>(`/research/${id}/messages`,{method:'POST',body:JSON.stringify({content})}),
  researchDecisions:(id:string)=>request<ResearchDecision[]>(`/research/${id}/decisions`),
  resolveResearchDecision:(id:string,decisionId:string,answer:string)=>request<ResearchDecision>(`/research/${id}/decisions/${decisionId}/resolve`,{method:'POST',body:JSON.stringify({answer})}),
  dismissResearchDecision:(id:string,decisionId:string)=>request<ResearchDecision>(`/research/${id}/decisions/${decisionId}/dismiss`,{method:'POST'}),
  generateSpecification:(id:string)=>request<ResearchProject>(`/research/${id}/specification/generate`,{method:'POST'}),
  updateSpecification:(id:string,specId:string,content:Record<string,any>)=>request<ResearchProject>(`/research/${id}/specification/${specId}`,{method:'PUT',body:JSON.stringify({content})}),
  approveSpecification:(id:string,specId:string)=>request<ResearchProject>(`/research/${id}/specification/${specId}/approve`,{method:'POST'}),
  createResearchImplementation:(id:string,client_id:string,force:boolean=false)=>request<{session:AgentSession;strategy_name:string;prompt:string}>(`/research/${id}/implementation`,{method:'POST',body:JSON.stringify({client_id,permission_mode:'acceptEdits',force})}),
  researchStrategyPreview:(id:string)=>request<{module:string;name:string;parameter_schema:Record<string,any>;data_requirements:Record<string,any>}>(`/research/${id}/strategy-preview`),
  publishResearchStrategy:(id:string)=>request<Strategy>(`/research/${id}/publish`,{method:'POST'}),
  researchRuns:(id:string)=>request<ResearchRun[]>(`/research/${id}/backtests`),
  createResearchRun:(id:string,data:unknown)=>request<{id:string;status:string;name:string}>(`/research/${id}/backtests`,{method:'POST',body:JSON.stringify(data)}),
  analyzeResearchRun:(id:string,runId:string)=>request<{role:string;content:string;run_id:string}>(`/research/${id}/backtests/${runId}/analyze`,{method:'POST'}),
  repairResearchRun:(id:string,runId:string,client_id:string)=>request<{session:AgentSession;strategy_name:string;prompt:string}>(`/research/${id}/backtests/${runId}/repair`,{method:'POST',body:JSON.stringify({client_id,permission_mode:'acceptEdits'})}),
  saveResearchConclusion:(id:string,data:{verdict:'SUPPORTED'|'REJECTED'|'INCONCLUSIVE';summary:string;next_step:string})=>request<ResearchProject>(`/research/${id}/conclusion`,{method:'PUT',body:JSON.stringify(data)}),
  archiveResearch:(id:string)=>request<ResearchProject>(`/research/${id}/archive`,{method:'POST'}),
  reopenResearch:(id:string)=>request<ResearchProject>(`/research/${id}/reopen`,{method:'POST'}),
  iterateResearch:(id:string,data:{target:'DISCUSSING'|'SPEC_REVIEW'|'READY_FOR_BACKTEST';reason:string})=>request<ResearchProject>(`/research/${id}/iterate`,{method:'POST',body:JSON.stringify(data)}),
  dataSymbols:(marketType:string)=>request<{symbol:string;base:string;quote:string}[]>(`/data/symbols?market_type=${marketType}`),
  createDataDownload:(data:unknown)=>request<any>('/data/downloads',{method:'POST',body:JSON.stringify(data)}),
  dataDownload:(id:string)=>request<any>('/data/downloads/'+id),
  runs:()=>request<Run[]>('/backtests'),run:(id:string)=>request<Run>('/backtests/'+id),chart:(id:string,symbol?:string)=>request<ChartData>(`/backtests/${id}/chart${symbol?'?symbol='+encodeURIComponent(symbol):''}`),createRun:(data:unknown)=>request<Run>('/backtests',{method:'POST',body:JSON.stringify(data)}),deleteRun:(id:string)=>request<void>('/backtests/'+id,{method:'DELETE'})
}
